CREATE TABLE CPANAME(ID BIGINT IDENTITY (0,1) PRIMARY KEY, NAME VARCHAR(15000) NOT NULL UNIQUE);
CREATE UNIQUE INDEX IDXCPANAME ON CPANAME(NAME);

CREATE TABLE CPAFILE(ID BIGINT IDENTITY (0,1) PRIMARY KEY,NAME VARCHAR NOT NULL,PARENT BIGINT NOT NULL,PATH VARCHAR(255) UNIQUE);
CREATE UNIQUE INDEX IDXCPAFILEPATH ON CPAFILE(PATH);
CREATE UNIQUE INDEX IDXNAMEPARENT ON CPAFILE(NAME, PARENT);


CREATE TABLE CPAENTITY(NODEID VARCHAR PRIMARY KEY,FILEID BIGINT NOT NULL,NAMEID BIGINT NOT NULL,FLAGS VARCHAR NOT NULL,SIZE BIGINT,LINE BIGINT,CCX BIGINT);

CREATE TABLE CPADEPENDENCY(NODEID VARCHAR PRIMARY KEY,FROMNODEID VARCHAR,TOFILEID BIGINT,TONODEID VARCHAR,FLAGS VARCHAR(10) NOT NULL,LINES VARCHAR(1000) NOT NULL);
CREATE INDEX IDXDEPNODE ON CPADEPENDENCY(FROMNODEID);

CREATE TABLE CPANAMETOENTITY(ID BIGINT IDENTITY (0,1) PRIMARY KEY,NAME VARCHAR(15000),NODEID VARCHAR,CONSTRAINT fk_name_entity FOREIGN KEY (NODEID) REFERENCES CPAENTITY(NODEID));
CREATE INDEX IDXNAMETOENTITY ON CPANAMETOENTITY(NAME);
CREATE UNIQUE INDEX IDXNAMEANDENTITY ON CPANAMETOENTITY(NAME, NODEID);

